[package]
edition = "2024"
authors = ["Maikel Wever <maikel@maikelwever.nl>", "Ales Katona <ales@katona.me>"]
categories = ["embedded", "hardware-support", "no-std"]
readme = "README.md"
description = "A platform agnostic driver to interface the MAX7219 (LED driver)"
documentation = "https://docs.rs/max7219"
keywords = ["embedded-hal-driver", "max7219", "ledcontrol"]
license = "MIT"
name = "max7219"
repository = "https://github.com/almindor/max7219"
version = "0.5.0"

[dependencies]
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
